#include "Std_Types.h"
#include "gpio.h"

#define SYSCLK_HSI 16000000UL
#define SYSCLK_HSE 25000000UL
#define SYSCLK_PLL

#define SYSCLK SYSCLK_HSI

#define USART_TRANSMITER 0x00002008
#define USART_RECEIVER 0x00002004
#define USART_TRANSMITER_RECEIVER 0x0000200C

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 0x00080000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00082000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00083000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 0x00084000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00086000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00087000

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 0x00800001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00820001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00830001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 0x00840001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00860001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00870001

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_1STOP 0x00080010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_1STOP 0x00082010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_1STOP 0x00083010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP 0x00084010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP 0x00086010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP 0x00087010

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_2STOP 0x00080011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_2STOP 0x00082011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_2STOP 0x00083011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP 0x00084011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP 0x00086011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP 0x00087011

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 0x00090000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00092000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00093000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 0x00094000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00096000
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00097000

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 0x00090001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00092001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00093001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 0x00094001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00096001
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00097001

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_1STOP 0x00090010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_1STOP 0x00092010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_1STOP 0x00093010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP 0x00094010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP 0x00096010
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP 0x00097010

#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_2STOP 0x00090011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_2STOP 0x00092011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_2STOP 0x00093011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP 0x00094011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP 0x00096011
#define USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP 0x00097011

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 0x00000000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00002000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00003000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 0x00004000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00006000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00007000

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 0x00000001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00002001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00003001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 0x00004001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00006001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00007001

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_1STOP 0x00000010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_1STOP 0x00002010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_1STOP 0x00003010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP 0x00004010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP 0x00006010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP 0x00007010

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_2STOP 0x00000011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_2STOP 0x00002011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_2STOP 0x00003011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP 0x00004011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP 0x00006011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP 0x00007011

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 0x00010000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00012000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00013000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 0x00014000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP 0x00016000
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP 0x00017000

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 0x00010001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00012001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00013001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 0x00014001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP 0x00016001
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP 0x00017001

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_1STOP 0x00010010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_1STOP 0x00012010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_1STOP 0x00013010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP 0x00014010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP 0x00016010
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP 0x00017010

#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_2STOP 0x00010011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_2STOP 0x00012011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_2STOP 0x00013011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP 0x00014011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP 0x00016011
#define USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP 0x00017011

#define USART_MODE_LIN_BREAK_10BITS 0x000040000
#define USART_MODE_LIN_BREAK_11BITS 0x000040200

#define USART_PARITY_INTERRUPT_FLAG                 0x00000100
#define USART_IDLE_INTERRUPT_FLAG                   0x00000010
#define USART_TXE_INTERRUPT_FLAG                    0x00000080
#define USART_TX_COMPLETE_INTERRUPT_FLAG            0x00000040
#define USART_RX_COMPLETE_INTERRUPT_FLAG            0x00000020
#define USART_LIN_BREAK_DETECTION_INTERRUPT_FLAG    0x10000040

typedef void (*USART_Cbf)(void);

typedef enum
{
    USART1,
    USART2,
    USART6,
    USART_COUNT
} Stm32f401_USART_enuChannel_t;

typedef struct
{
    GPIO_Cfg_t TXPin;
    GPIO_Cfg_t RXPin;
    Stm32f401_USART_enuChannel_t Channel;
    u32 DataDirection;
    u32 Mode;
    u32 BaudRate;

} USART_strCfg_t;

typedef enum
{
	USART_enuBAUD_1200 = 1200,
    USART_enuBAUD_2400 = 2400,
    USART_enuBAUD_4800 = 4800,
    USART_enuBAUD_9600 = 9600,
    USART_enuBAUD_14_4k = 14400,
    USART_enuBAUD_19_2K = 19200,
    USART_enuBAUD_28_8k = 28800,
    USART_enuBAUD_38_4K = 38400,
    USART_enuBAUD_57_6k = 57600,
    USART_enuBAUD_76_8k = 76800,
    USART_enuBAUD_115_2K = 115200,
    USART_enuBAUD_230_4k = 230400,
    USART_enuBAUD_250K = 250000,
    USART_enuBAUD_0_5M = 500000,
    USART_enuBAUD_1M = 1000000

} USART_BaudRate;

typedef enum
{
    USART_enuOK,
    USART_enuNOK,
    USART_enuNULLPTR,
    USART_enuWrong_Cfg,
    USART_enuRX_DONE,
    USART_enuRX_BUSY,
    USART_enuTX_DONE,
    USART_enuTX_BUSY

} USART_enuErrorStatus;

typedef enum
{
    USART_enuIDLE,
    USART_enuBUSY
} USART_enuREQ_STATE_t;

typedef struct
{
    u8 *Buffer;
    u32 Size;
    u32 Idx;
    USART_Cbf NotifyCbf;
    USART_enuREQ_STATE_t Status;
} USART_strREQ_Handler_t;


/*****************************************************************
 * Return : Void
 * Input  : Channel Enumeration type identifying the desired usart 
 * Description : Send Synchronous Break
 * ***************************************************************
*/
void USART_vidSendBreak(Stm32f401_USART_enuChannel_t Channel);

/*****************************************************************
 * Return : Error status if wrong configurations
 * Input  : Address pointer to created object for the post compile configurations
 * Description : Initialize USART Peripheral 
 * ***************************************************************
 *  Configuration Options:
 *
 *  DataDirection ->
 *  -USART_TRANSMITER
 *  -USART_RECEIVER
 *  -USART_TRANSMITER_RECEIVER
 * ---------------------------------------------------------------
*  Modes ->
*
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP 
    \
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__8_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_NOPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_EVENPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_IDLEWAKEUP_ODDPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__8_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP 

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_1STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_1STOP

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_NOBREAK_2STOP 
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_NOBREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_NOBREAK_2STOP

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_1STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_1STOP

    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_NOPARITY_BREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_EVENPARITY_BREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_IDLEWAKEUP_ODDPARITY_BREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_NOPARITY_BREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_EVENPARITY_BREAK_2STOP
    -USART_MODE_ASYNC_OVERSAMPLE__16_CHARSIZE__9_ADDRESSWAKEUP_ODDPARITY_BREAK_2STOP
        -------------------------------------------------------------
*  BaudrRate-> Enum  option of USART_BaudRates
*/
USART_enuErrorStatus USART_Init(USART_strCfg_t *Add_pstrUSART_cfg);

/*****************************************************************
 * Return : Error status if wrong configurations
 * Input  : -Channel Enumeration type identifying the desired usart 
 *          -Desired interrupt flag option ->
 *              -USART_PARITY_INTERRUPT_FLAG 
                -USART_IDLE_INTERRUPT_FLAG 
                -USART_TXE_INTERRUPT_FLAG 
                -USART_TX_COMPLETE_INTERRUPT_FLAG 
                -USART_RX_COMPLETE_INTERRUPT_FLAG 
                -USART_LIN_BREAK_DETECTION_INTERRUPT_FLAG
 * Description : Enable the desired interrupt flag for the selected peripheral channel
 * ***************************************************************
*/
USART_enuErrorStatus USART_EnableInterrupts(Stm32f401_USART_enuChannel_t Channel, u32 Cpy_u32InterruptFlag);
/*****************************************************************
 * Return : Error status if wrong configurations
 * Input  : -Channel Enumeration type identifying the desired usart 
 *          -Desired interrupt flag option ->
 *              -USART_PARITY_INTERRUPT_FLAG 
                -USART_IDLE_INTERRUPT_FLAG 
                -USART_TXE_INTERRUPT_FLAG 
                -USART_TX_COMPLETE_INTERRUPT_FLAG 
                -USART_RX_COMPLETE_INTERRUPT_FLAG 
                -USART_LIN_BREAK_DETECTION_INTERRUPT_FLAG
 * Description : Disable desired interrupt flag for the selected peripheral channnel
 * ***************************************************************
*/
USART_enuErrorStatus USART_DisableInterrupts(Stm32f401_USART_enuChannel_t Channel, u32 Cpy_u32InterruptFlag);

/*****************************************************************
 * Return : Error status if wrong configurations or if receive is done or busy
 * Input  : -Channel Enumeration type identifying the desired usart 
 * Description : Checks if the receive process is done or still busy
 * ***************************************************************
*/
USART_enuErrorStatus USART_IsRX(Stm32f401_USART_enuChannel_t Channel);
/*****************************************************************
 * Return : Error status if wrong configurations or if send is done or busy
 * Input  : -Channel Enumeration type identifying the desired usart 
 * Description : Checks if the send process is done or still busy
 * ***************************************************************
*/
USART_enuErrorStatus USART_IsTX(Stm32f401_USART_enuChannel_t Channel);
/*****************************************************************
 * Return : Error status if wrong configurations or the request status
 * 
 * Input  : -u8 Pointer to the desired buffer to be sent
 *          -u32 size of the buffer
 *          -void Callback function to notify the user after send is done
 *          -Channel Enumeration type identifying the desired usart 
 * 
 * Description : Handles send request needed for the user
 * ***************************************************************
*/
USART_enuErrorStatus USART_SendBufferAsyncZeroCopy(u8 *Add_pu8Buffer, u32 Cpy_u32Size, USART_Cbf NotifyCbf, Stm32f401_USART_enuChannel_t Channel);
/*****************************************************************
 * Return : Error status if wrong configurations or the request status
 * 
 * Input  : -u8 Pointer to the desired buffer to be sent
 *          -u32 size of the buffer
 *          -void Callback function to notify the user after send is done
 *          -Channel Enumeration type identifying the desired usart 
 * 
 * Description : Handles Receive request needed for the user
 * ***************************************************************
*/
USART_enuErrorStatus USART_ReceiveBufferAsyncZeroCopy(u8 *Add_pu8Buffer, u32 Cpy_u32Size, USART_Cbf NotifyCbf, Stm32f401_USART_enuChannel_t Channel);
